//! Writes the docs site's generated reference pages into `--out <dir>`; the docs repo checks them in and its
//! drift check regenerates them at each release tag.

mod settings_page;
mod shortcuts_page;

use std::path::PathBuf;

const HEADER: &str = "<!-- generated by docs_gen; do not edit -->\n\n";

fn main() {
    if let Err(error) = run() {
        eprintln!("docs_gen: {error}");
        std::process::exit(1);
    }
}

fn run() -> Result<(), String> {
    let out = out_dir()?;
    std::fs::create_dir_all(&out).map_err(|error| format!("{}: {error}", out.display()))?;
    let pages = [
        ("settings.md", settings_page::render()?),
        ("shortcuts.md", shortcuts_page::render()),
    ];
    for (name, body) in pages {
        let path = out.join(name);
        std::fs::write(&path, format!("{HEADER}{body}"))
            .map_err(|error| format!("{}: {error}", path.display()))?;
    }
    Ok(())
}

fn out_dir() -> Result<PathBuf, String> {
    let mut args = std::env::args().skip(1);
    match (args.next().as_deref(), args.next()) {
        (Some("--out"), Some(dir)) => Ok(PathBuf::from(dir)),
        _ => Err("usage: docs_gen --out <dir>".into()),
    }
}

/// Inline code that survives a Markdown table and the site's template syntax.
fn code(text: &str) -> String {
    let escaped = table_cell(text);
    if escaped.contains('`') {
        format!("`` {escaped} ``")
    } else {
        format!("`{escaped}`")
    }
}

fn table_cell(text: &str) -> String {
    text.replace('|', "\\|")
}
