pub mod buffer;
pub mod completion;
pub mod display;
pub mod fold;
pub mod grammar_packages;
pub mod highlight;
pub mod indent;
mod injection;
pub mod language;
pub mod line_widths;
pub mod movement;
pub mod outline;
mod parsers;
pub mod registry;
pub mod search;
pub mod snippet;
pub mod syntax;
pub mod theme;
pub mod transform;
pub mod wrap;

pub use buffer::EditorBuffer;
pub use highlight::Lang;
pub use syntax::Syntax;
pub use theme::Theme;
