pub mod buffer;
pub mod completion;
pub mod display;
pub mod fold;
pub mod highlight;
pub mod indent;
mod injection;
pub mod language;
pub mod movement;
pub mod outline;
pub mod search;
pub mod syntax;
pub mod theme;
pub mod transform;
pub mod wrap;

pub use buffer::EditorBuffer;
pub use highlight::Lang;
pub use syntax::Syntax;
pub use theme::Theme;
