package services

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

func CopyFiles(repoDir, worktreeDir string, patterns []string) {
	for _, pattern := range patterns {
		if strings.Contains(pattern, "*") {
			matches := globFiles(repoDir, pattern)
			for _, relPath := range matches {
				copySingleFile(filepath.Join(repoDir, relPath), filepath.Join(worktreeDir, relPath))
			}
		} else {
			copySingleFile(filepath.Join(repoDir, pattern), filepath.Join(worktreeDir, pattern))
		}
	}
}

func copySingleFile(src, dest string) {
	info, err := os.Stat(src)
	if err != nil || info.IsDir() {
		return
	}
	if _, err := os.Stat(dest); err == nil {
		return
	}
	_ = os.MkdirAll(filepath.Dir(dest), 0o755)
	data, err := os.ReadFile(src)
	if err == nil {
		_ = os.WriteFile(dest, data, info.Mode())
	}
}

func ApplyEnvOverridesToDir(dir string, envOverrides []EnvVar, envFileName string) {
	if len(envOverrides) == 0 {
		return
	}
	lines := []string{"# Auto-generated by pom. Do not commit."}
	for _, ev := range envOverrides {
		lines = append(lines, ev.Key+"="+ev.Value)
	}
	_ = os.MkdirAll(dir, 0o755)
	_ = os.WriteFile(filepath.Join(dir, envFileName), []byte(strings.Join(lines, "\n")+"\n"), 0o644)
}

func ApplyEnvOverrides(worktreeDir string, envOverrides []EnvVar, envFileName string, skipSubdirs ...string) {
	if len(envOverrides) == 0 {
		return
	}
	skipSet := make(map[string]bool)
	for _, s := range skipSubdirs {
		abs := filepath.Join(worktreeDir, s)
		skipSet[filepath.Clean(abs)] = true
	}
	for _, dir := range findEnvDirs(worktreeDir) {
		if skipSet[filepath.Clean(dir)] {
			continue
		}
		lines := []string{"# Auto-generated by pom. Do not commit."}
		for _, ev := range envOverrides {
			lines = append(lines, ev.Key+"="+ev.Value)
		}
		_ = os.WriteFile(filepath.Join(dir, envFileName), []byte(strings.Join(lines, "\n")+"\n"), 0o644)
	}
}

func findEnvDirs(worktreeDir string) []string {
	var dirs []string
	if fileExists(filepath.Join(worktreeDir, ".env")) || fileExists(filepath.Join(worktreeDir, ".env.development")) {
		dirs = append(dirs, worktreeDir)
	}
	entries, err := os.ReadDir(filepath.Join(worktreeDir, "apps"))
	if err == nil {
		for _, e := range entries {
			if e.IsDir() {
				appDir := filepath.Join(worktreeDir, "apps", e.Name())
				if fileExists(filepath.Join(appDir, ".env")) {
					dirs = append(dirs, appDir)
				}
			}
		}
	}
	return dirs
}

func EnsureGlobalGitignore() {
	home, err := os.UserHomeDir()
	if err != nil {
		return
	}
	gitignorePath := filepath.Join(home, ".gitignore_global")

	excludes := ""
	if out, err := exec.Command("git", "config", "--global", "core.excludesfile").Output(); err == nil {
		excludes = strings.TrimSpace(string(out))
	}

	if excludes == "" {
		_ = exec.Command("git", "config", "--global", "core.excludesfile", gitignorePath).Run()
	}

	target := gitignorePath
	if excludes != "" {
		target = excludes
	}
	content, _ := os.ReadFile(target)
	contentStr := string(content)

	ignoreFiles := []string{
		"docker-compose.shared.yml",
		".env.local",
		".env.*.local",
		"pnpm-lock.yaml",
		".pom-workspace.json",
	}
	var toAdd []string
	for _, f := range ignoreFiles {
		if !strings.Contains(contentStr, f) {
			toAdd = append(toAdd, f)
		}
	}
	if len(toAdd) > 0 {
		f, err := os.OpenFile(target, os.O_CREATE|os.O_APPEND|os.O_WRONLY, 0o644)
		if err != nil {
			return
		}
		defer f.Close()
		if !strings.Contains(contentStr, "# pom") {
			fmt.Fprintln(f, "\n# pom worktree")
		}
		for _, file := range toAdd {
			fmt.Fprintln(f, file)
		}
	}
}

func globFiles(repoDir, pattern string) []string {
	fullPattern := filepath.Join(repoDir, pattern)
	matches, err := filepath.Glob(fullPattern)
	if err != nil {
		return nil
	}
	var result []string
	for _, m := range matches {
		rel, err := filepath.Rel(repoDir, m)
		if err == nil && !strings.HasPrefix(rel, "..") {
			result = append(result, rel)
		}
	}
	return result
}

var fileExists = FileExists
