package services

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/pomelohq/pomelo/internal/paths"

	"github.com/pomelohq/pomelo/internal/config"
)

type SlotAllocation struct {
	Instance int `json:"instance"`
	Slot     int `json:"slot"`
}

type ServiceSlots struct {
	Slots         map[string]SlotAllocation `json:"slots"`
	InstanceCount int                       `json:"instance_count"`
}

func slotStatePath() string { return paths.StatePath("shared_slots.json") }

func LoadSlotAllocations() map[string]*ServiceSlots {
	data, err := os.ReadFile(slotStatePath())
	if err != nil {
		return make(map[string]*ServiceSlots)
	}
	var allocs map[string]*ServiceSlots
	if json.Unmarshal(data, &allocs) != nil {
		return make(map[string]*ServiceSlots)
	}
	return allocs
}

func saveSlotAllocations(allocs map[string]*ServiceSlots) {
	path := slotStatePath()
	_ = os.MkdirAll(filepath.Dir(path), 0o755)
	data, _ := json.MarshalIndent(allocs, "", "  ")
	_ = os.WriteFile(path, data, 0o644)
}

func withSlotLock(fn func()) {
	lockPath := paths.StatePath("slots.lock")
	_ = os.MkdirAll(filepath.Dir(lockPath), 0o755)

	for {
		f, err := os.OpenFile(lockPath, os.O_WRONLY|os.O_CREATE|os.O_EXCL, 0o644)
		if err == nil {
			fmt.Fprintf(f, "%d", os.Getpid())
			f.Close()
			break
		}
		if info, err := os.Stat(lockPath); err == nil {
			if time.Since(info.ModTime()) > 10*time.Second {
				_ = os.Remove(lockPath)
				continue
			}
		}
		time.Sleep(50 * time.Millisecond)
	}
	fn()
	_ = os.Remove(lockPath)
}

func AllocateSlot(serviceName, worktreeKey string, capacity, basePort uint16) (instance, slot int, port uint16) {
	withSlotLock(func() {
		allocs := LoadSlotAllocations()
		svc, ok := allocs[serviceName]
		if !ok {
			svc = &ServiceSlots{Slots: make(map[string]SlotAllocation), InstanceCount: 1}
			allocs[serviceName] = svc
		}

		if existing, ok := svc.Slots[worktreeKey]; ok {
			instance = existing.Instance
			slot = existing.Slot
			port = basePort + uint16(existing.Instance)
			return
		}

		cap := int(capacity)
		for inst := 0; inst < svc.InstanceCount; inst++ {
			usedInInst := 0
			usedSlots := make(map[int]bool)
			for _, a := range svc.Slots {
				if a.Instance == inst {
					usedInInst++
					usedSlots[a.Slot] = true
				}
			}
			if usedInInst < cap {
				s := 0
				for ; s < cap; s++ {
					if !usedSlots[s] {
						break
					}
				}
				svc.Slots[worktreeKey] = SlotAllocation{Instance: inst, Slot: s}
				saveSlotAllocations(allocs)
				instance = inst
				slot = s
				port = basePort + uint16(inst)
				return
			}
		}

		newInst := svc.InstanceCount
		svc.InstanceCount++
		svc.Slots[worktreeKey] = SlotAllocation{Instance: newInst, Slot: 0}
		saveSlotAllocations(allocs)
		instance = newInst
		slot = 0
		port = basePort + uint16(newInst)
	})
	return
}

func ReleaseSlot(serviceName, worktreeKey string) {
	withSlotLock(func() {
		allocs := LoadSlotAllocations()
		svc, ok := allocs[serviceName]
		if !ok {
			return
		}
		delete(svc.Slots, worktreeKey)
		for svc.InstanceCount > 1 {
			last := svc.InstanceCount - 1
			found := false
			for _, a := range svc.Slots {
				if a.Instance == last {
					found = true
					break
				}
			}
			if found {
				break
			}
			svc.InstanceCount--
		}
		saveSlotAllocations(allocs)
	})
}

func MaxInstanceCount(serviceName string) int {
	allocs := LoadSlotAllocations()
	if svc, ok := allocs[serviceName]; ok {
		return svc.InstanceCount
	}
	return 1
}

func GenerateSharedCompose(configDir, session string, sharedServices map[string]*config.SharedServiceDef) string {
	EnsureSharedNetwork()

	var b strings.Builder
	b.WriteString("# Auto-generated by pom. Do not edit.\n")
	fmt.Fprintf(&b, "name: %s-shared\n\n", session)

	var volumeNames []string
	volumeSet := make(map[string]bool)

	b.WriteString("services:\n")
	for name, svc := range sharedServices {
		instances := 1
		if svc.Capacity != nil {
			instances = MaxInstanceCount(name)
		}

		for inst := 0; inst < instances; inst++ {
			svcName := name
			if inst > 0 {
				svcName = fmt.Sprintf("%s-%d", name, inst+1)
			}
			fmt.Fprintf(&b, "  %s:\n", svcName)
			fmt.Fprintf(&b, "    image: %s\n", svc.Image)

			if svc.Command != "" {
				fmt.Fprintf(&b, "    command: %s\n", svc.Command)
			}

			if len(svc.Ports) > 0 {
				b.WriteString("    ports:\n")
				for portIdx, port := range svc.Ports {
					containerP := ContainerPort(port)
					hostPort := SharedPortAt(name, portIdx) + inst
					fmt.Fprintf(&b, "      - \"%d:%s\"\n", hostPort, containerP)
				}
			}

			if len(svc.Environment) > 0 {
				b.WriteString("    environment:\n")
				for k, v := range svc.Environment {
					fmt.Fprintf(&b, "      %s: \"%s\"\n", k, v)
				}
			}

			if len(svc.Volumes) > 0 {
				b.WriteString("    volumes:\n")
				for _, vol := range svc.Volumes {
					adjustedVol := vol
					if inst > 0 {
						parts := strings.SplitN(vol, ":", 2)
						if len(parts) == 2 && !strings.HasPrefix(parts[0], ".") && !strings.HasPrefix(parts[0], "/") {
							adjustedVol = fmt.Sprintf("%s-%d:%s", parts[0], inst+1, parts[1])
						}
					}
					fmt.Fprintf(&b, "      - %s\n", adjustedVol)
					if volName, _, ok := strings.Cut(adjustedVol, ":"); ok {
						if !strings.HasPrefix(volName, ".") && !strings.HasPrefix(volName, "/") {
							if !volumeSet[volName] {
								volumeSet[volName] = true
								volumeNames = append(volumeNames, volName)
							}
						}
					}
				}
			}

			if svc.Healthcheck != nil {
				b.WriteString("    healthcheck:\n")
				interval := svc.Healthcheck.Interval
				if interval == "" {
					interval = "10s"
				}
				timeout := svc.Healthcheck.Timeout
				if timeout == "" {
					timeout = "3s"
				}
				retries := svc.Healthcheck.Retries
				if retries == 0 {
					retries = 3
				}
				fmt.Fprintf(&b, "      interval: %s\n", interval)
				fmt.Fprintf(&b, "      timeout: %s\n", timeout)
				fmt.Fprintf(&b, "      retries: %d\n", retries)
			}

			fmt.Fprintf(&b, "    networks:\n      - default\n      - %s\n", SharedNetworkName)
			b.WriteString("    restart: unless-stopped\n\n")
		}
	}

	fmt.Fprintf(&b, "networks:\n  %s:\n    external: true\n", SharedNetworkName)

	if len(volumeNames) > 0 {
		b.WriteString("\nvolumes:\n")
		for _, vol := range volumeNames {
			fmt.Fprintf(&b, "  %s:\n    driver: local\n", vol)
		}
	}

	path := filepath.Join(configDir, "docker-compose.shared.yml")
	_ = os.WriteFile(path, []byte(b.String()), 0o644)
	return path
}

func StartSharedServices(configDir, session string, serviceNames []string) {
	composeFile := filepath.Join(configDir, "docker-compose.shared.yml")
	if !fileExists(composeFile) {
		return
	}
	args := []string{"compose", "-f", composeFile, "-p", session + "-shared", "up", "-d"}
	args = append(args, serviceNames...)
	cmd := exec.Command("docker", args...)
	cmd.Dir = configDir
	_ = cmd.Run()
}

func EnsureWorkspaceDatabases(cfg *config.Config, branch string) {
	var pg *config.SharedServiceDef
	for _, svc := range cfg.SharedServices {
		if svc.DBUser != "" {
			pg = svc
			break
		}
	}
	host := cfg.SharedHost("postgres")
	port := uint16(SharedPort("postgres"))
	if port == 0 {
		port = 5432
	}
	user, pw := "postgres", "postgres"
	if pg != nil {
		if pg.Host != "" {
			host = pg.Host
		}
		if pg.DBUser != "" {
			user = pg.DBUser
		}
		if pg.DBPassword != "" {
			pw = pg.DBPassword
		}
	}

	var dbNames []string
	for _, dirName := range cfg.RepoOrder {
		dir := cfg.Repos[dirName]
		if dir == nil || !dir.HasWorktreeConfig() {
			continue
		}
		for _, sref := range dir.SharedSvcRefs {
			if sref.DBName != "" {
				dbNames = append(dbNames, ResolveBranchTokens(sref.DBName, branch))
			}
		}
		for _, tpl := range dir.Databases {
			dbNames = append(dbNames, cfg.Session+"_"+ResolveBranchTokens(tpl, branch))
		}
	}
	if len(dbNames) > 0 {
		CreateSharedDBsBatch(host, port, dbNames, user, pw)
	}
}

func CreateSharedDBsBatch(host string, port uint16, dbNames []string, user, password string) []string {
	if len(dbNames) == 0 {
		return nil
	}
	container := findPostgresContainer(port)
	var results []string
	for _, db := range dbNames {
		sql := fmt.Sprintf(`CREATE DATABASE "%s"`, db)
		var out []byte
		var err error
		if container != "" {
			out, err = exec.Command("docker", "exec", container, "psql", "-U", user, "-c", sql).CombinedOutput()
		} else {
			extraHost := fmt.Sprintf("--add-host=%s:host-gateway", host)
			connURL := fmt.Sprintf("postgresql://%s:%s@%s:%d/postgres", user, password, host, port)
			out, err = exec.Command("docker", "run", "--rm", extraHost, "postgres:16-alpine", "psql", connURL, "-c", sql).CombinedOutput()
		}
		stderr := string(out)
		if err == nil {
			results = append(results, "created: "+db)
		} else if strings.Contains(stderr, "already exists") {
			results = append(results, "exists: "+db)
		} else {
			results = append(results, "failed: "+db+": "+strings.TrimSpace(stderr))
		}
		enablePgStatStatements(container, host, port, user, password, db)
	}
	return results
}

func enablePgStatStatements(container, host string, port uint16, user, password, db string) {
	const sql = "CREATE EXTENSION IF NOT EXISTS pg_stat_statements"
	if container != "" {
		_ = exec.Command("docker", "exec", container, "psql", "-U", user, "-d", db, "-c", sql).Run()
		return
	}
	extraHost := fmt.Sprintf("--add-host=%s:host-gateway", host)
	connURL := fmt.Sprintf("postgresql://%s:%s@%s:%d/%s", user, password, host, port, db)
	_ = exec.Command("docker", "run", "--rm", extraHost, "postgres:16-alpine", "psql", connURL, "-c", sql).Run()
}

func DropSharedDBsBatch(host string, port uint16, dbNames []string, user, password string) bool {
	if len(dbNames) == 0 {
		return true
	}
	container := findPostgresContainer(port)
	ok := true
	for _, db := range dbNames {
		terminateSQL := fmt.Sprintf("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = '%s' AND pid <> pg_backend_pid()", db)
		dropSQL := fmt.Sprintf(`DROP DATABASE IF EXISTS "%s"`, db)

		if container != "" {
			_ = exec.Command("docker", "exec", container, "psql", "-U", user, "-c", terminateSQL).Run()
			if out, err := exec.Command("docker", "exec", container, "psql", "-U", user, "-c", dropSQL).CombinedOutput(); err != nil {
				ok = false
				fmt.Printf("\n    drop %s failed: %s", db, strings.TrimSpace(string(out)))
			}
		} else {
			extraHost := fmt.Sprintf("--add-host=%s:host-gateway", host)
			connURL := fmt.Sprintf("postgresql://%s:%s@%s:%d/postgres", user, password, host, port)
			_ = exec.Command("docker", "run", "--rm", extraHost, "postgres:16-alpine", "psql", connURL, "-c", terminateSQL).Run()
			if out, err := exec.Command("docker", "run", "--rm", extraHost, "postgres:16-alpine", "psql", connURL, "-c", dropSQL).CombinedOutput(); err != nil {
				ok = false
				fmt.Printf("\n    drop %s failed: %s", db, strings.TrimSpace(string(out)))
			}
		}
	}
	return ok
}

func ListSharedDBs(host string, port uint16, user, password string) []string {
	sql := "SELECT datname FROM pg_database WHERE datistemplate = false AND datname NOT IN ('postgres')"
	container := findPostgresContainer(port)
	var out []byte
	var err error
	if container != "" {
		out, err = exec.Command("docker", "exec", container, "psql", "-U", user, "-t", "-A", "-c", sql).CombinedOutput()
	} else {
		extraHost := fmt.Sprintf("--add-host=%s:host-gateway", host)
		connURL := fmt.Sprintf("postgresql://%s:%s@%s:%d/postgres", user, password, host, port)
		out, err = exec.Command("docker", "run", "--rm", extraHost, "postgres:16-alpine", "psql", connURL, "-t", "-A", "-c", sql).CombinedOutput()
	}
	if err != nil {
		return nil
	}
	var dbs []string
	for _, line := range strings.Split(strings.TrimSpace(string(out)), "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			dbs = append(dbs, line)
		}
	}
	return dbs
}

func findPostgresContainer(port uint16) string {
	out, err := exec.Command("docker", "ps", "-q",
		"--filter", fmt.Sprintf("publish=%d", port),
		"--filter", "status=running").Output()
	if err != nil {
		return ""
	}
	lines := strings.Split(strings.TrimSpace(string(out)), "\n")
	if len(lines) > 0 && lines[0] != "" {
		return lines[0]
	}
	return ""
}
