//! A workspace's env reaches its services two ways: written into each repo's env files (so tools run by
//! hand see it too) and injected straight into the service's holder. Both resolve the same config.

use std::path::{Path, PathBuf};

use indexmap::IndexMap;
use pom_config::{Config, Dir};
use pom_env::{EnvSources, ResolveContext};
use pom_layout::WorkspaceState;

const HEADER: &str = "# Auto-generated by pom. Do not commit.";
const DEFAULT_ENV_FILE: &str = ".env.local";

/// One workspace's env, resolved against the machine state in `sources`.
pub struct WorkspaceEnv<'a> {
    pub config: &'a Config,
    pub project_root: &'a Path,
    pub branch: &'a str,
    pub sources: &'a dyn EnvSources,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct EnvLine {
    pub key: String,
    pub value: String,
    pub source: String,
    pub secret: bool,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ServiceExplain {
    pub repo: String,
    pub alias: String,
    pub service: String,
    pub cmd: String,
    pub databases: IndexMap<String, String>,
    pub env: Vec<EnvLine>,
}

impl WorkspaceEnv<'_> {
    fn folder(&self) -> PathBuf {
        pom_layout::workspace_folder(self.project_root, self.branch)
    }

    fn ws_key(&self) -> String {
        pom_env::port_ws_key(self.branch)
    }

    /// Database key -> session-prefixed, branch-resolved database name.
    pub fn db_names(&self, dir: &Dir) -> IndexMap<String, String> {
        dir.databases
            .iter()
            .map(|(key, template)| {
                let name = pom_env::resolve_branch_tokens(template, self.branch);
                (key.clone(), format!("{}_{name}", self.config.session))
            })
            .collect()
    }

    fn resolve(
        &self,
        env: &IndexMap<String, String>,
        env_name: &str,
        db_names: &IndexMap<String, String>,
    ) -> Vec<(String, String)> {
        let ws_key = self.ws_key();
        ResolveContext {
            config: self.config,
            branch: self.branch,
            ws_key: &ws_key,
            env_name,
            db_names,
            sources: self.sources,
        }
        .resolve_env(env)
    }

    /// The repo env overlaid with the service's own, resolved, for injecting into its holder.
    pub fn service_env(&self, repo: &str, service: &str) -> Vec<(String, String)> {
        let Some(dir) = self.config.repos.get(repo) else {
            return Vec::new();
        };
        let Some(own) = dir.services.get(service) else {
            return Vec::new();
        };
        let state = WorkspaceState::load(&self.folder());
        let env_name = state.service_env(&format!("{}/{service}", alias(repo, dir)));
        let mut merged = dir.env.clone();
        merged.extend(own.env.clone());
        self.resolve(&merged, env_name, &self.db_names(dir))
    }

    pub fn explain_service(
        &self,
        repo: &str,
        service: &str,
        env_name: &str,
    ) -> Option<ServiceExplain> {
        let dir = self.config.repos.get(repo)?;
        let own = dir.services.get(service)?;
        let mut merged = dir.env.clone();
        merged.extend(own.env.clone());
        let databases = self.db_names(dir);
        let env = self
            .resolve(&merged, env_name, &databases)
            .into_iter()
            .map(|(key, value)| {
                let template = merged.get(&key).map_or("", String::as_str);
                let source = if dir.own_env.contains_key(&key) || own.env.contains_key(&key) {
                    "own".to_string()
                } else {
                    dir.presets
                        .iter()
                        .find(|name| {
                            self.config
                                .presets
                                .get(name.as_str())
                                .is_some_and(|preset| preset.env.contains_key(&key))
                        })
                        .map_or_else(String::new, |name| format!("preset:{name}"))
                };
                let secret = template
                    .split("{{")
                    .skip(1)
                    .any(|token| token.trim_start().starts_with("secret."));
                EnvLine {
                    key,
                    value,
                    source,
                    secret,
                }
            })
            .collect();
        Some(ServiceExplain {
            repo: repo.to_string(),
            alias: alias(repo, dir).to_string(),
            service: service.to_string(),
            cmd: own.active_cmd("").to_string(),
            databases,
            env,
        })
    }

    /// The repo-level env (no service overlay), for commands run in the repo's worktree.
    pub fn repo_env(&self, repo: &str) -> Vec<(String, String)> {
        let Some(dir) = self.config.repos.get(repo) else {
            return Vec::new();
        };
        let state = WorkspaceState::load(&self.folder());
        let env_name = state
            .service_envs
            .get(alias(repo, dir))
            .map_or("", String::as_str);
        self.resolve(&dir.env, env_name, &self.db_names(dir))
    }

    /// Rewrites every repo's env files in the workspace. A workspace without a folder has nothing to
    /// write into and is skipped.
    pub fn write_env_files(&self) -> std::io::Result<()> {
        let folder = self.folder();
        if !folder.is_dir() {
            return Ok(());
        }
        let state = WorkspaceState::load(&folder);
        for (repo, dir) in &self.config.repos {
            let worktree = folder.join(repo);
            if !worktree.is_dir() || !dir.has_worktree_config() {
                continue;
            }
            let alias = alias(repo, dir);
            let repo_env_name = state.service_envs.get(alias).map_or("", String::as_str);
            let db_names = self.db_names(dir);
            let entries = dir.env_file_entries();
            let service_dirs: Vec<PathBuf> = dir
                .services
                .values()
                .filter(|service| !service.dir.is_empty())
                .map(|service| worktree.join(&service.dir))
                .collect();
            for entry in &entries {
                let mut env = dir.env.clone();
                env.extend(entry.env.clone());
                let resolved = self.resolve(&env, repo_env_name, &db_names);
                for target in env_dirs(&worktree) {
                    if !service_dirs.contains(&target) {
                        write_env_file(&target, &entry.file, &resolved)?;
                    }
                }
            }
            let file = entries
                .first()
                .map_or(DEFAULT_ENV_FILE, |entry| entry.file.as_str());
            for (name, service) in &dir.services {
                if service.dir.is_empty() && service.env.is_empty() {
                    continue;
                }
                let mut env = dir.env.clone();
                if service.dir.is_empty() {
                    for entry in entries.iter().filter(|entry| entry.file == file) {
                        env.extend(entry.env.clone());
                    }
                }
                env.extend(service.env.clone());
                if env.is_empty() {
                    continue;
                }
                let env_name = state.service_env(&format!("{alias}/{name}"));
                let resolved = self.resolve(&env, env_name, &db_names);
                let target = if service.dir.is_empty() {
                    worktree.clone()
                } else {
                    worktree.join(&service.dir)
                };
                std::fs::create_dir_all(&target)?;
                write_env_file(&target, file, &resolved)?;
            }
        }
        Ok(())
    }
}

pub(crate) fn alias<'a>(repo: &'a str, dir: &'a Dir) -> &'a str {
    if dir.alias.is_empty() {
        repo
    } else {
        &dir.alias
    }
}

/// Where a repo keeps env files today: its root and any `apps/<name>` that already has a `.env`. A repo
/// without one gets nothing written, so we never scatter files into projects that load env otherwise.
fn env_dirs(worktree: &Path) -> Vec<PathBuf> {
    let mut dirs = Vec::new();
    if worktree.join(".env").is_file() || worktree.join(".env.development").is_file() {
        dirs.push(worktree.to_path_buf());
    }
    if let Ok(entries) = std::fs::read_dir(worktree.join("apps")) {
        let mut apps: Vec<PathBuf> = entries
            .flatten()
            .filter(|entry| entry.file_type().is_ok_and(|kind| kind.is_dir()))
            .map(|entry| entry.path())
            .filter(|app| app.join(".env").is_file())
            .collect();
        apps.sort();
        dirs.extend(apps);
    }
    dirs
}

fn write_env_file(dir: &Path, file: &str, env: &[(String, String)]) -> std::io::Result<()> {
    if env.is_empty() {
        return Ok(());
    }
    let mut text = String::from(HEADER);
    text.push('\n');
    for (key, value) in env {
        text.push_str(key);
        text.push('=');
        text.push_str(value);
        text.push('\n');
    }
    std::fs::write(dir.join(file), text)
}
