//! Shared services (a Postgres, a Redis, ...) run once per project in Docker, not per workspace: one
//! compose project `<session>-shared` from a generated `docker-compose.shared.yml` at the project root,
//! the same file and names the previous core used so either can manage the running stack.

use std::collections::HashSet;
use std::path::{Path, PathBuf};
use std::process::{Command, Output};

use pom_config::{Config, SharedServiceDef};

use crate::control::{ServiceError, ServiceRunner};

pub const COMPOSE_FILE: &str = "docker-compose.shared.yml";
pub const SHARED_NETWORK: &str = "pomelo-shared";
/// Shared services keep their usual host port when it is free, searching this far above it.
const PREFERRED_SPAN: u16 = 100;
const POSTGRES: &str = "postgres";
const DEFAULT_PG_PORT: u16 = 5432;
/// Used to reach a Postgres not published by one of our containers.
const PSQL_IMAGE: &str = "postgres:16-alpine";

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SharedAction {
    Start,
    Stop,
    Restart,
}

impl ServiceRunner {
    pub fn compose_project(&self) -> String {
        format!("{}-shared", self.session)
    }

    pub fn compose_file(&self) -> PathBuf {
        self.project_root.join(COMPOSE_FILE)
    }

    /// The host port a shared service is reached on: its lease, else the stable fallback.
    pub fn shared_host_port(&self, name: &str) -> u16 {
        pom_env::EnvSources::shared_port(self, name).unwrap_or(0)
    }

    /// Leases the shared services' ports, makes sure the shared network exists and rewrites the
    /// compose file.
    pub fn write_shared_compose(&self, config: &Config) -> Result<PathBuf, ServiceError> {
        self.ensure_network()?;
        self.reserve_shared_ports(config);
        let text = self.shared_compose(config);
        let path = self.compose_file();
        std::fs::write(&path, text)?;
        Ok(path)
    }

    /// The compose file's contents: one service per instance (a capacity service runs as many as its
    /// slots need), each on its leased host port plus the instance index.
    pub fn shared_compose(&self, config: &Config) -> String {
        let mut out = String::from("# Auto-generated by pom. Do not edit.\n");
        out.push_str(&format!("name: {}\n\nservices:\n", self.compose_project()));
        let mut volumes: Vec<String> = Vec::new();
        for (name, def) in &config.shared_services {
            let instances = if def.capacity.is_some() {
                self.slots.instance_count(name).max(1)
            } else {
                1
            };
            for instance in 0..instances {
                let service = if instance == 0 {
                    name.clone()
                } else {
                    format!("{name}-{}", instance + 1)
                };
                out.push_str(&format!("  {service}:\n    image: {}\n", def.image));
                if !def.command.is_empty() {
                    out.push_str(&format!("    command: {}\n", def.command));
                }
                if !def.ports.is_empty() {
                    out.push_str("    ports:\n");
                    for (index, mapping) in def.ports.iter().enumerate() {
                        let host = self.shared_port_at(name, index) + instance;
                        out.push_str(&format!("      - \"{host}:{}\"\n", container_port(mapping)));
                    }
                }
                if !def.environment.is_empty() {
                    out.push_str("    environment:\n");
                    for (key, value) in &def.environment {
                        out.push_str(&format!("      {key}: \"{value}\"\n"));
                    }
                }
                if !def.volumes.is_empty() {
                    out.push_str("    volumes:\n");
                    for volume in &def.volumes {
                        let volume = instance_volume(volume, instance);
                        out.push_str(&format!("      - {volume}\n"));
                        if let Some((source, _)) = volume.split_once(':') {
                            let named = !source.starts_with('.') && !source.starts_with('/');
                            if named && !volumes.iter().any(|known| known == source) {
                                volumes.push(source.to_string());
                            }
                        }
                    }
                }
                if let Some(check) = &def.healthcheck {
                    let or = |value: &str, fallback: &str| {
                        if value.is_empty() {
                            fallback.to_string()
                        } else {
                            value.to_string()
                        }
                    };
                    let retries = if check.retries == 0 { 3 } else { check.retries };
                    out.push_str(&format!(
                        "    healthcheck:\n      interval: {}\n      timeout: {}\n      retries: {retries}\n",
                        or(&check.interval, "10s"),
                        or(&check.timeout, "3s"),
                    ));
                }
                out.push_str(&format!(
                    "    networks:\n      - default\n      - {SHARED_NETWORK}\n    restart: unless-stopped\n\n"
                ));
            }
        }
        out.push_str(&format!(
            "networks:\n  {SHARED_NETWORK}:\n    external: true\n"
        ));
        if !volumes.is_empty() {
            out.push_str("\nvolumes:\n");
            for volume in volumes {
                out.push_str(&format!("  {volume}:\n    driver: local\n"));
            }
        }
        out
    }

    /// Brings the whole shared stack up (a no-op for services already running).
    pub fn ensure_shared(&self, config: &Config) -> Result<(), ServiceError> {
        if config.shared_services.is_empty() {
            return Ok(());
        }
        let file = self.write_shared_compose(config)?;
        self.compose(&file, &["up", "-d"])
    }

    pub fn shared_action(
        &self,
        config: &Config,
        name: &str,
        action: SharedAction,
    ) -> Result<(), ServiceError> {
        if !config.shared_services.contains_key(name) {
            return Err(ServiceError::UnknownService(name.to_string()));
        }
        let file = self.write_shared_compose(config)?;
        match action {
            SharedAction::Start => self.compose(&file, &["up", "-d", name]),
            SharedAction::Restart => self.compose(&file, &["up", "-d", "--force-recreate", name]),
            SharedAction::Stop => self.compose(&file, &["stop", name]),
        }
    }

    pub fn stop_shared(&self) -> Result<(), ServiceError> {
        self.compose(&self.compose_file(), &["stop"])
    }

    /// Shared services whose container runs right now; empty when Docker is unreachable.
    pub fn shared_running(&self) -> HashSet<String> {
        let file = self.compose_file();
        if !file.is_file() {
            return HashSet::new();
        }
        let args = self.compose_args(&file, &["ps", "--services", "--filter", "status=running"]);
        match self.docker(&args) {
            Ok(output) if output.status.success() => String::from_utf8_lossy(&output.stdout)
                .lines()
                .map(str::trim)
                .filter(|line| !line.is_empty())
                .map(str::to_string)
                .collect(),
            _ => HashSet::new(),
        }
    }

    /// Creates the workspace's databases in the shared Postgres; existing ones are left alone.
    pub fn ensure_databases(&self, config: &Config, branch: &str) -> Result<(), ServiceError> {
        let names = database_names(config, branch);
        if names.is_empty() {
            return Ok(());
        }
        let postgres = config
            .shared_services
            .values()
            .find(|def| !def.db_user.is_empty());
        let pick = |value: Option<&String>, fallback: &str| {
            value
                .filter(|value| !value.is_empty())
                .cloned()
                .unwrap_or_else(|| fallback.to_string())
        };
        let host = pick(postgres.map(|def| &def.host), "localhost");
        let user = pick(postgres.map(|def| &def.db_user), POSTGRES);
        let password = pick(postgres.map(|def| &def.db_password), POSTGRES);
        let port = match self.shared_host_port(POSTGRES) {
            0 => DEFAULT_PG_PORT,
            port => port,
        };
        let container = self.published_container(port);
        let mut failures = Vec::new();
        for name in names {
            let create = format!("CREATE DATABASE \"{name}\"");
            let output = self.psql(
                container.as_deref(),
                &host,
                port,
                &user,
                &password,
                POSTGRES,
                &create,
            )?;
            let stderr = String::from_utf8_lossy(&output.stdout).into_owned()
                + &String::from_utf8_lossy(&output.stderr);
            if !output.status.success() && !stderr.contains("already exists") {
                failures.push(format!("{name}: {}", stderr.trim()));
                continue;
            }
            let extension = "CREATE EXTENSION IF NOT EXISTS pg_stat_statements";
            if let Err(error) = self.psql(
                container.as_deref(),
                &host,
                port,
                &user,
                &password,
                &name,
                extension,
            ) {
                eprintln!("services: pg_stat_statements on {name}: {error}");
            }
        }
        if failures.is_empty() {
            Ok(())
        } else {
            Err(ServiceError::Io(std::io::Error::other(format!(
                "could not create databases: {}",
                failures.join("; ")
            ))))
        }
    }

    fn ensure_network(&self) -> Result<(), ServiceError> {
        let output = self.docker(&["network".into(), "create".into(), SHARED_NETWORK.into()])?;
        let stderr = String::from_utf8_lossy(&output.stderr);
        if output.status.success() || stderr.contains("already exists") {
            Ok(())
        } else {
            Err(docker_failure(&output))
        }
    }

    fn reserve_shared_ports(&self, config: &Config) {
        let mut names: Vec<&String> = config.shared_services.keys().collect();
        names.sort();
        for name in names {
            let Some(def) = config.shared_services.get(name) else {
                continue;
            };
            for index in 0..def.ports.len().max(1) {
                let base = host_port_base(def, index);
                let key = pom_ports::shared_key(name, index);
                if self
                    .ports
                    .acquire_preferred(&key, base, PREFERRED_SPAN)
                    .is_none()
                {
                    eprintln!("services: no free port for shared {name}");
                }
            }
        }
    }

    fn shared_port_at(&self, name: &str, index: usize) -> u16 {
        self.ports
            .port_of(&pom_ports::shared_key(name, index))
            .unwrap_or_else(|| {
                let lease_name = if index == 0 {
                    name.to_string()
                } else {
                    format!("{name}#{index}")
                };
                pom_env::stable_shared_port(&self.session, &lease_name)
            })
    }

    fn published_container(&self, port: u16) -> Option<String> {
        let args = [
            "ps",
            "-q",
            "--filter",
            &format!("publish={port}"),
            "--filter",
            "status=running",
        ]
        .map(str::to_string);
        let output = self.docker(&args).ok()?;
        String::from_utf8_lossy(&output.stdout)
            .lines()
            .next()
            .map(str::trim)
            .filter(|id| !id.is_empty())
            .map(str::to_string)
    }

    #[allow(clippy::too_many_arguments)]
    fn psql(
        &self,
        container: Option<&str>,
        host: &str,
        port: u16,
        user: &str,
        password: &str,
        database: &str,
        sql: &str,
    ) -> Result<Output, ServiceError> {
        let args: Vec<String> = match container {
            Some(container) => [
                "exec", container, "psql", "-U", user, "-d", database, "-c", sql,
            ]
            .map(str::to_string)
            .to_vec(),
            None => vec![
                "run".into(),
                "--rm".into(),
                format!("--add-host={host}:host-gateway"),
                PSQL_IMAGE.into(),
                "psql".into(),
                format!("postgresql://{user}:{password}@{host}:{port}/{database}"),
                "-c".into(),
                sql.into(),
            ],
        };
        self.docker(&args)
    }

    fn compose_args(&self, file: &Path, rest: &[&str]) -> Vec<String> {
        let mut args = vec![
            "compose".to_string(),
            "-f".to_string(),
            file.to_string_lossy().into_owned(),
            "-p".to_string(),
            self.compose_project(),
        ];
        args.extend(rest.iter().map(|arg| arg.to_string()));
        args
    }

    fn compose(&self, file: &Path, rest: &[&str]) -> Result<(), ServiceError> {
        let output = self.docker(&self.compose_args(file, rest))?;
        if output.status.success() {
            Ok(())
        } else {
            Err(docker_failure(&output))
        }
    }

    fn docker(&self, args: &[String]) -> Result<Output, ServiceError> {
        Command::new(&self.docker)
            .args(args)
            .current_dir(&self.project_root)
            .env("PATH", crate::tool_path())
            .output()
            .map_err(|error| {
                ServiceError::Io(std::io::Error::new(
                    error.kind(),
                    format!("docker: {error}"),
                ))
            })
    }
}

/// Database names of a workspace: shared-service refs as named, and `databases:` session-prefixed.
pub fn database_names(config: &Config, branch: &str) -> Vec<String> {
    let mut names = Vec::new();
    for dir in config.repos.values() {
        if !dir.has_worktree_config() {
            continue;
        }
        for shared in &dir.shared_refs {
            if !shared.db_name.is_empty() {
                names.push(pom_env::resolve_branch_tokens(&shared.db_name, branch));
            }
        }
        for template in dir.databases.values() {
            names.push(format!(
                "{}_{}",
                config.session,
                pom_env::resolve_branch_tokens(template, branch)
            ));
        }
    }
    names
}

fn docker_failure(output: &Output) -> ServiceError {
    let mut text = String::from_utf8_lossy(&output.stderr).trim().to_string();
    if text.is_empty() {
        text = String::from_utf8_lossy(&output.stdout).trim().to_string();
    }
    ServiceError::Io(std::io::Error::other(format!("docker: {text}")))
}

/// `host:container` -> `container`; a bare port is both.
fn container_port(mapping: &str) -> &str {
    mapping
        .split_once(':')
        .map_or(mapping, |(_, container)| container)
}

/// The usual host port of the `index`th mapping, tried first when leasing.
fn host_port_base(def: &SharedServiceDef, index: usize) -> u16 {
    def.ports
        .get(index)
        .and_then(|mapping| mapping.split([':', '/']).next())
        .and_then(|port| port.trim().parse().ok())
        .unwrap_or(0)
}

/// Extra instances get their own named volume (`data-2:/var/lib/...`); bind mounts are shared.
fn instance_volume(volume: &str, instance: u16) -> String {
    if instance == 0 {
        return volume.to_string();
    }
    match volume.split_once(':') {
        Some((source, target)) if !source.starts_with('.') && !source.starts_with('/') => {
            format!("{source}-{}:{target}", instance + 1)
        }
        _ => volume.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn volumes_and_ports_per_instance() {
        assert_eq!(
            instance_volume("pgdata:/var/lib/pg", 0),
            "pgdata:/var/lib/pg"
        );
        assert_eq!(
            instance_volume("pgdata:/var/lib/pg", 1),
            "pgdata-2:/var/lib/pg"
        );
        assert_eq!(instance_volume("./init:/docker", 2), "./init:/docker");
        assert_eq!(container_port("5432:5432"), "5432");
        assert_eq!(container_port("6379"), "6379");
    }
}
