//! Which env files a workspace gets and what goes in them.

use pom_config::Config;
use pom_env::{EnvSources, SlotAllocation};
use pom_services::WorkspaceEnv;

struct Pinned;

impl EnvSources for Pinned {
    fn shared_port(&self, _name: &str) -> Option<u16> {
        Some(25432)
    }
    fn service_port(&self, _ws_key: &str, service_key: &str) -> Option<u16> {
        (service_key == "api~server").then_some(41000)
    }
    fn slot(&self, _shared_name: &str, _ws_key: &str) -> Option<SlotAllocation> {
        Some(SlotAllocation {
            instance: 0,
            slot: 3,
        })
    }
    fn secret(&self, _session: &str, name: &str) -> Option<String> {
        (name == "TOKEN").then(|| "s3cret".to_string())
    }
}

#[test]
fn writes_file_keyed_env_into_existing_env_dirs_and_service_dirs() {
    let temp = tempfile::tempdir().expect("temp");
    let root = temp.path();
    let worktree = root.join("workspace--feat-a/api");
    std::fs::create_dir_all(worktree.join("apps/admin")).expect("apps");
    std::fs::create_dir_all(worktree.join("apps/bare")).expect("apps");
    std::fs::write(worktree.join(".env"), "").expect(".env");
    std::fs::write(worktree.join("apps/admin/.env"), "").expect("admin .env");
    std::fs::write(
        root.join("pom.yml"),
        r#"session: demo
shared_services:
  postgres:
    image: postgres:16
  redis:
    image: redis:7
    capacity: 16
repos:
  api:
    databases:
      main: "app_{{branch.safe}}"
    env:
      "*":
        DB: "{{db.main.url}}"
        TOKEN: "{{secret.TOKEN}}"
      .env.local:
        REDIS_DB: "{{shared.redis.slot}}"
      .env.test.local:
        MODE: test
    services:
      server:
        type: backend
        cmd: rails s
      worker:
        dir: apps/worker
        cmd: sidekiq
        env:
          SERVER: "{{api.server.port}}"
"#,
    )
    .expect("pom.yml");
    let config = Config::load(&root.join("pom.yml")).expect("config");
    WorkspaceEnv {
        config: &config,
        project_root: root,
        branch: "feat-a",
        sources: &Pinned,
    }
    .write_env_files()
    .expect("write");

    let read = |path: &str| std::fs::read_to_string(worktree.join(path)).unwrap_or_default();
    let db = "DB=postgres://postgres:postgres@127.0.0.1:25432/demo_app_feat-a";
    assert_eq!(
        read(".env.local"),
        format!("# Auto-generated by pom. Do not commit.\n{db}\nREDIS_DB=3\nTOKEN=s3cret\n")
    );
    assert!(read(".env.test.local").contains("MODE=test"));
    assert!(read("apps/admin/.env.local").contains("REDIS_DB=3"));
    assert!(!worktree.join("apps/bare/.env.local").exists());
    let worker = read("apps/worker/.env.local");
    assert!(worker.contains("SERVER=41000"), "{worker}");
    assert!(worker.contains(db), "{worker}");
    assert!(
        !worker.contains("REDIS_DB"),
        "a service with its own dir only gets the base env: {worker}"
    );
}

#[test]
fn a_workspace_without_a_folder_is_left_alone() {
    let temp = tempfile::tempdir().expect("temp");
    std::fs::write(
        temp.path().join("pom.yml"),
        "session: demo\nrepos:\n  api:\n    env:\n      A: b\n",
    )
    .expect("pom.yml");
    let config = Config::load(&temp.path().join("pom.yml")).expect("config");
    let env = WorkspaceEnv {
        config: &config,
        project_root: temp.path(),
        branch: "missing",
        sources: &Pinned,
    };
    env.write_env_files().expect("no-op");
    assert_eq!(
        env.service_env("api", "none"),
        Vec::<(String, String)>::new()
    );
}

#[test]
fn explains_where_each_service_value_comes_from() {
    let temp = tempfile::tempdir().expect("temp");
    let root = temp.path();
    std::fs::write(
        root.join("pom.yml"),
        r#"session: demo
presets:
  rails:
    env:
      RAILS_ENV: development
      LOG: info
repos:
  api:
    alias: be
    preset: [rails]
    databases:
      main: "app_{{branch.safe}}"
    env:
      LOG: debug
      TOKEN: "{{secret.TOKEN}}"
    services:
      server:
        cmd: rails s
        env:
          PORT: "{{be.server.port}}"
"#,
    )
    .expect("pom.yml");
    let config = Config::load(&root.join("pom.yml")).expect("config");
    let env = WorkspaceEnv {
        config: &config,
        project_root: root,
        branch: "feat/a",
        sources: &Pinned,
    };
    let explain = env.explain_service("api", "server", "").expect("explain");
    assert_eq!(explain.alias, "be");
    assert_eq!(explain.cmd, "rails s");
    assert_eq!(
        explain.databases.get("main").map(String::as_str),
        Some("demo_app_feat_a")
    );
    let line = |key: &str| {
        explain
            .env
            .iter()
            .find(|line| line.key == key)
            .cloned()
            .expect(key)
    };
    assert_eq!(line("RAILS_ENV").source, "preset:rails");
    assert_eq!(line("LOG").source, "own", "the repo overrides the preset");
    assert_eq!(line("LOG").value, "debug");
    assert!(line("TOKEN").secret);
    assert_eq!(line("TOKEN").value, "s3cret");
    assert_eq!(line("PORT").source, "own");
    assert!(env.explain_service("api", "missing", "").is_none());
}
