//! Shared services against a stand-in `docker` that records its arguments and answers `ps`.

use std::os::unix::fs::PermissionsExt;
use std::path::{Path, PathBuf};

use pom_config::Config;
use pom_paths::StateDir;
use pom_ptyhost::SocketDir;
use pom_services::{RunnerOptions, ServiceRunner, SharedAction, SlotStore};

struct Fixture {
    temp: tempfile::TempDir,
    runner: ServiceRunner,
    config: Config,
}

const CONFIG: &str = r#"session: demo
shared_services:
  postgres:
    image: postgres:16
    ports: ["5432:5432"]
    environment:
      POSTGRES_PASSWORD: secret
    volumes: ["pgdata:/var/lib/postgresql/data"]
    db_user: app
    db_password: secret
  redis:
    image: redis:7
    ports: ["6379:6379"]
    capacity: 16
    healthcheck:
      interval: 5s
repos:
  api:
    databases:
      main: "api_{{branch.safe}}"
    services:
      server: rails s
"#;

impl Fixture {
    /// `answers` is the fake docker's stdout for `compose ... ps`, `ps -q` (a published container) and
    /// `exec` (psql) in that order of lines, separated by `|`.
    fn new(ps_output: &str, container: &str, psql_fails_with: &str) -> Fixture {
        let temp = tempfile::tempdir().expect("temp");
        let root = temp.path().join("project");
        std::fs::create_dir_all(&root).expect("root");
        std::fs::write(root.join("pom.yml"), CONFIG).expect("pom.yml");
        let config = Config::load(&root.join("pom.yml")).expect("config");
        let docker = fake_docker(temp.path(), ps_output, container, psql_fails_with);
        let runner = ServiceRunner::new(RunnerOptions {
            project_root: root,
            session: "demo".into(),
            state: StateDir::new(temp.path().join("state")),
            holders: SocketDir::new(temp.path().join("s")),
            binary: PathBuf::from("/nonexistent"),
            docker,
        });
        Fixture {
            temp,
            runner,
            config,
        }
    }

    fn calls(&self) -> Vec<String> {
        std::fs::read_to_string(self.temp.path().join("docker.log"))
            .unwrap_or_default()
            .lines()
            .map(str::to_string)
            .collect()
    }
}

fn fake_docker(dir: &Path, ps_output: &str, container: &str, psql_fails_with: &str) -> PathBuf {
    let script = dir.join("docker");
    let log = dir.join("docker.log");
    std::fs::write(
        &script,
        format!(
            r#"#!/bin/sh
echo "$*" >> '{log}'
case "$*" in
  "network create"*) echo "network with name pomelo-shared already exists" >&2; exit 1 ;;
  compose*" ps "*) printf '{ps_output}' ;;
  "ps -q"*) printf '{container}' ;;
  "exec "*"CREATE DATABASE"*) if [ -n '{psql_fails_with}' ]; then echo '{psql_fails_with}' >&2; exit 1; fi ;;
esac
exit 0
"#,
            log = log.display()
        ),
    )
    .expect("script");
    std::fs::set_permissions(&script, std::fs::Permissions::from_mode(0o755)).expect("chmod");
    script
}

#[test]
fn the_compose_file_matches_the_previous_core_layout() {
    let fixture = Fixture::new("", "", "");
    let slots = SlotStore::new(StateDir::new(fixture.temp.path().join("state")));
    for ws in ["ws-a", "ws-b"] {
        slots.allocate("redis", ws, 1).expect("slot");
    }
    let file = fixture
        .runner
        .write_shared_compose(&fixture.config)
        .expect("compose");
    let text = std::fs::read_to_string(file).expect("read");
    let pg = fixture.runner.shared_host_port("postgres");
    let redis = fixture.runner.shared_host_port("redis");
    assert_eq!(pg, 5432, "a free well-known port is kept");
    let expected = format!(
        r#"# Auto-generated by pom. Do not edit.
name: demo-shared

services:
  postgres:
    image: postgres:16
    command: postgres -c shared_preload_libraries=pg_stat_statements
    ports:
      - "{pg}:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "secret"
      POSTGRES_DB: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - default
      - pomelo-shared
    restart: unless-stopped

  redis:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - "{redis}:6379"
    volumes:
      - shared_redis:/data
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - default
      - pomelo-shared
    restart: unless-stopped

  redis-2:
    image: redis:7
    command: redis-server --appendonly yes
    ports:
      - "{redis_2}:6379"
    volumes:
      - shared_redis-2:/data
    healthcheck:
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - default
      - pomelo-shared
    restart: unless-stopped

networks:
  pomelo-shared:
    external: true

volumes:
  pgdata:
    driver: local
  shared_redis:
    driver: local
  shared_redis-2:
    driver: local
"#,
        redis_2 = redis + 1
    );
    assert_eq!(text, expected);
    assert_eq!(fixture.calls()[0], "network create pomelo-shared");
}

#[test]
fn actions_and_status_go_through_the_shared_compose_project() {
    let fixture = Fixture::new("postgres\\n", "", "");
    fixture
        .runner
        .shared_action(&fixture.config, "redis", SharedAction::Restart)
        .expect("restart");
    fixture
        .runner
        .shared_action(&fixture.config, "redis", SharedAction::Stop)
        .expect("stop");
    let running = fixture.runner.shared_running();
    assert!(running.contains("postgres") && !running.contains("redis"));
    let file = fixture.runner.compose_file();
    let compose = format!("compose -f {} -p demo-shared", file.display());
    let calls = fixture.calls();
    assert!(
        calls.contains(&format!("{compose} up -d --force-recreate redis")),
        "{calls:?}"
    );
    assert!(
        calls.contains(&format!("{compose} stop redis")),
        "{calls:?}"
    );
    assert!(calls.contains(&format!("{compose} ps --services --filter status=running")));
    assert!(fixture
        .runner
        .shared_action(&fixture.config, "nope", SharedAction::Start)
        .is_err());
}

#[test]
fn databases_are_created_in_the_published_postgres_container() {
    let fixture = Fixture::new(
        "",
        "c0ffee\\n",
        "ERROR:  database \"demo_api_feat_x\" already exists",
    );
    fixture
        .runner
        .write_shared_compose(&fixture.config)
        .expect("compose");
    fixture
        .runner
        .ensure_databases(&fixture.config, "feat/x")
        .expect("an existing database is fine");
    let calls = fixture.calls();
    assert!(
        calls.contains(
            &"exec c0ffee psql -U app -d postgres -c CREATE DATABASE \"demo_api_feat_x\""
                .to_string()
        ),
        "{calls:?}"
    );
    assert!(calls.contains(
        &"exec c0ffee psql -U app -d demo_api_feat_x -c CREATE EXTENSION IF NOT EXISTS pg_stat_statements"
            .to_string()
    ));
}

#[test]
fn a_real_database_failure_is_reported() {
    let fixture = Fixture::new("", "c0ffee\\n", "FATAL: role does not exist");
    let error = fixture
        .runner
        .ensure_databases(&fixture.config, "main")
        .expect_err("failure");
    assert!(error.to_string().contains("role does not exist"), "{error}");
}
