//! Opening a coding agent in a workspace: Claude Code runs in a holder named like the previous core's
//! (`ws-<session>-<branch>-claude-raw`) with a session id derived from the workspace, so either app
//! reattaches to the same conversation, and it gets pom's MCP server and a short system prompt.

use std::path::{Path, PathBuf};

use pom_paths::StateDir;
use sha1::{Digest, Sha1};

use crate::claude::mcp_config_json;

const CLAUDE_HOLDER: &str = "claude-raw";

const CONFIG_VARIABLES: &str = "POM CONFIG VARIABLES - dot-notation ONLY. NEVER write colon forms ({{var:...}} {{host:...}} {{port:...}} {{conn:...}} {{db:...}} {{user:...}} {{pass:...}} {{slot:...}} {{url:...}} {{ws:...}}); config load REJECTS them. Migrate any you find:
- {{shared.<name>.url}} - shared service conn (user:pass@host:port); also .host .port .user .pass .slot (redis DB index)
- {{db.<name>}} - named per-branch database (session-prefixed); {{db.<name>.url}} full postgres URL. Declare the repo's `databases:` map to create them.
- {{<repo>.<service>.url}} / .path / .host / .port / .ws - another repo service's address (.path = same-origin /_pom_dev/<repo>/<svc>); switch local/remote by listing it under an `environments` profile
- {{secret.<NAME>}} - stored secret (never inline secrets); {{slot.<name>}}; {{branch.safe}} / {{branch.host}} / {{branch.hash}}; {{bind_ip}}
NEVER author `proxy:`/`webhook:` (Pomelo auto-routes /_pom_dev/<repo>/<svc> + webhooks /<repo>/<svc>) or app config (`ui`/`code_agents`). pom.yml is config to RUN the project only. Full grammar: docs/config-schema.md.
Examples: DATABASE_URL: postgresql://{{shared.postgres.url}}/{{db.main}}?schema=public; REDIS_URL: redis://{{shared.redis.host}}:{{shared.redis.port}}/{{shared.redis.slot}}; OPENSEARCH_URL: http://{{shared.opensearch.host}}:{{shared.opensearch.port}}; MINIO_URL: http://{{shared.minio.host}}:{{shared.minio.port}}";

const ENV_IS_GENERATED: &str = "IMPORTANT: `.env.local` (and any per-workspace env file) is GENERATED by Pomelo from the `env:` section of the config (`pom.yml` / `pom.d`) with the templating resolved for this branch - editing it directly is WRONG and gets overwritten on the next generate/reload. To change an env value, edit the `env:` in the Pomelo config via the config tools (config_files -> config_file_get/config_file_set for split pom.d, else config_set), then config_validate + reload so pom regenerates the env file. Never hand-edit `.env.local`.";

/// Appended to the agent's own system prompt: what pom offers and the config grammar.
pub fn system_prompt() -> String {
    format!(
        "You have the `pom` MCP tools for THIS workspace's real environment - services, ports, databases (connection strings), service_logs, run_in_env / run_shortcut (use the project's own commands, `commands`, over hand-rolled shell), and the config tools. {ENV_IS_GENERATED} Prefer these tools over guessing.\n{CONFIG_VARIABLES}"
    )
}

const ONBOARD_FIRST_TURN: &str = "Onboard this session now: analyze every cloned repo and author a correct, complete pom.yml (frameworks, monorepo apps, all processes, setup, shared services from every compose incl. extends, and repo aliases). Loop config_doctor until zero errors. Then call config_normalize as the FINAL step (it strips removed keys, migrates colon->dot, and tidies into pom.d), and confirm what you defined.";

pub fn onboard_system_prompt() -> String {
    format!(
        "You are Pomelo's onboarding agent. A new session was just scaffolded: its repos are cloned into workspace--<default>/<repo>, and a ROUGH SEED pom.yml exists (naive framework guesses - often wrong or empty). Your job: analyze EVERY repo and author a correct, complete, RUNNABLE pom.yml.
AUTONOMY: do it end to end with the tools - the pom MCP config tools, Read/Grep/Glob/Bash. Never ask the user to edit a file or run a command; DO it. Loop gather -> act -> verify until config_doctor reports ZERO errors. Never declare done while a config_doctor finding remains.
WHAT A CORRECT CONFIG NEEDS, per repo:
- LANGUAGE/FRAMEWORK: read package.json, Gemfile, go.mod, requirements.txt/pyproject.toml, pom.xml. The seed may miss a stack entirely; you must fill it.
- MONOREPO: if package.json has `workspaces`, or there's turbo.json / pnpm-workspace.yaml / nx.json / an apps/ dir, it's a monorepo with MULTIPLE apps. Create ONE pom service per runnable app (e.g. `turbo run dev --filter=<app>` for each app under apps/*), not a single `web`.
- MULTIPLE PROCESSES: one repo often runs several long-lived processes. Read package.json scripts, Procfile, and the docker-compose service commands - make a pom service for EACH (web, worker, sidekiq, sqs-consumer, scheduler, ...), not just one.
- SETUP: the real install command (bundle install / pnpm install / npm ci / go mod download / pip install), from the lockfile + language. INCLUDE codegen the app needs to boot: e.g. `prisma generate` (a Nest/Prisma app crashes without a generated client), graphql codegen, protobuf. Put these in `setup:` after install.
- MIGRATIONS: backends usually need their DB schema created before they boot. Set `migrate:` to the real command when the repo uses migrations - rails db:migrate; prisma migrate deploy (or prisma db push); sequel/knex/alembic (alembic upgrade head). Set `seed:` when there's a seed script. Without this a fresh DB throws 'relation/table does not exist'.
- SHARED SERVICES: read ALL docker-compose files (docker-compose.yml, compose.yml, AND any file referenced via `extends: {{file: ...}}` such as docker-compose-services.yml). Map every infra container (postgres/redis/minio/opensearch/elasticsearch/mysql/mongo/rabbitmq/kafka) to a shared_services entry. `extends`-based services have NO inline image - follow the extends to the real image. Do NOT miss opensearch/secondary-postgres just because the top compose only lists them via extends.
- ALIASES: give each repo a short, memorable alias (strip a common prefix, e.g. acme-api -> api). Aliases are how the user and tools address repos.
- ENV WIRING (critical - do NOT skip): every shared service you declare MUST be wired into the repos that use it via the `env:` section, using the templates below. Read each repo's real env needs from its docker-compose environment/x-environment block and its .env.example, then map them. A declared shared service with no env reference is a bug - config_doctor flags it as unwired and you must fix it. This is the difference between a config that merely validates and one that actually RUNS.
{CONFIG_VARIABLES}
- IMPORTED SECRETS: a project already on disk has its gitignored .env values imported into the secret store. Call secrets_list to see the available names and wire each into the config env as {{{{secret.NAME}}}} - EXCEPT infra endpoints (DATABASE_URL/REDIS_URL/...) which should point at the shared services via {{{{shared.*}}}}, not a stale imported value.
- VERIFY (best-effort): after config_doctor is clean, if deps are installed and Docker is up, start ONE service per repo (service_start) and read its logs (service_logs) to confirm it boots; fix any startup/env error and re-check. If the environment isn't ready to run, skip this rather than forcing it.
{ENV_IS_GENERATED}
TOOLS: config_files -> config_file_get/config_file_set for split pom.d, else config_get/config_set. Every write is validated against the merged config before it lands. After each write, call config_doctor and keep fixing until 0 errors. Prefer the project's own commands (`commands`/`run_shortcut`) over hand-rolled shell.
BREVITY: extremely terse. Report only: repo -> detected stack -> what you wrote, as short fragments. No preamble. When config_doctor is clean, one line confirming the project is runnable + the services you defined."
    )
}

/// A stable UUID (version 5 layout) for a key, so a workspace always resumes the same conversation.
pub fn session_id(key: &str) -> String {
    let digest = Sha1::digest(format!("pom-session:{key}").as_bytes());
    let mut bytes = [0u8; 16];
    bytes.copy_from_slice(&digest[..16]);
    bytes[6] = (bytes[6] & 0x0f) | 0x50;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    let hex: String = bytes.iter().map(|byte| format!("{byte:02x}")).collect();
    format!(
        "{}-{}-{}-{}-{}",
        &hex[0..8],
        &hex[8..12],
        &hex[12..16],
        &hex[16..20],
        &hex[20..32]
    )
}

fn shell_quote(text: &str) -> String {
    format!("'{}'", text.replace('\'', r"'\''"))
}

/// Where the `claude` binary is. An app started from Finder has a minimal PATH and a login shell does
/// not read `~/.zshrc`, so the installer's usual locations are probed first.
pub fn resolve_claude(home: &Path, tool_path: &str) -> String {
    let executable = |path: &Path| {
        use std::os::unix::fs::PermissionsExt;
        path.metadata()
            .is_ok_and(|meta| meta.is_file() && meta.permissions().mode() & 0o111 != 0)
    };
    let on_path = tool_path
        .split(':')
        .map(|dir| Path::new(dir).join("claude"))
        .find(|candidate| executable(candidate));
    let known = [
        home.join(".local/bin/claude"),
        home.join(".claude/local/claude"),
        PathBuf::from("/opt/homebrew/bin/claude"),
        PathBuf::from("/usr/local/bin/claude"),
    ];
    on_path
        .or_else(|| known.into_iter().find(|candidate| executable(candidate)))
        .map_or_else(
            || "claude".to_string(),
            |path| path.to_string_lossy().into_owned(),
        )
}

/// Claude keeps a session's transcript under `~/.claude/projects/<cwd with separators as dashes>/`.
fn transcript_exists(home: &Path, cwd: &Path, id: &str) -> bool {
    let text = cwd.to_string_lossy();
    let slashes = text.replace('/', "-");
    let everything: String = text
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect();
    [slashes, everything].iter().any(|dir| {
        home.join(".claude/projects")
            .join(dir)
            .join(format!("{id}.jsonl"))
            .is_file()
    })
}

/// A workspace's agent: which holder runs it, where, and with what command.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct AgentLaunch {
    pub holder: String,
    pub cwd: PathBuf,
    pub argv: Vec<String>,
    pub title: String,
}

pub struct LaunchContext<'a> {
    pub state: &'a StateDir,
    pub home: &'a Path,
    /// The app binary, which serves `mcp` for the agent.
    pub binary: &'a Path,
    pub tool_path: &'a str,
    pub session: &'a str,
    pub branch: &'a str,
    pub is_main: bool,
    /// The workspace folder the agent works in.
    pub cwd: &'a Path,
}

/// Claude Code for the workspace, resuming its conversation when one exists.
pub fn claude_launch(context: &LaunchContext<'_>) -> AgentLaunch {
    let key = if context.is_main {
        format!("main:{}", context.branch)
    } else {
        format!("ws:{}", context.branch)
    };
    let id = session_id(&format!("chat:{key}"));
    let session_flag = if transcript_exists(context.home, context.cwd, &id) {
        "--resume"
    } else {
        "--session-id"
    };
    let claude = resolve_claude(context.home, context.tool_path);
    let mcp = mcp_config_json(context.state, context.binary, context.branch);
    let image_cache = context.home.join(".claude/image-cache");
    let script = format!(
        "export PATH={path}; export TERM=xterm-256color COLORTERM=truecolor; unsetopt monitor 2>/dev/null; cd {cwd} && exec {claude} {session_flag} {id} --mcp-config {mcp} --add-dir {images} --append-system-prompt {prompt}",
        path = shell_quote(context.tool_path),
        cwd = shell_quote(&context.cwd.to_string_lossy()),
        claude = shell_quote(&claude),
        mcp = shell_quote(&mcp),
        images = shell_quote(&image_cache.to_string_lossy()),
        prompt = shell_quote(&system_prompt()),
    );
    AgentLaunch {
        holder: format!(
            "ws-{}-{}-{CLAUDE_HOLDER}",
            context.session.replace('/', "_"),
            context.branch.replace('/', "_")
        ),
        cwd: context.cwd.to_path_buf(),
        argv: vec!["zsh".into(), "-c".into(), script],
        title: "Claude".into(),
    }
}

/// Whether holder `name` runs a coding agent for `branch` of `session`: the workspace agent, a numbered
/// extra one, or a task agent (fixer, onboarder).
pub fn is_agent_holder(name: &str, session: &str, branch: &str) -> bool {
    let prefix = format!(
        "ws-{}-{}-",
        session.replace('/', "_"),
        branch.replace('/', "_")
    );
    let Some(role) = name.strip_prefix(&prefix) else {
        return false;
    };
    [CLAUDE_HOLDER, "fixer", "onboarder"].iter().any(|agent| {
        role.strip_prefix(agent).is_some_and(|rest| {
            rest.is_empty()
                || rest.strip_prefix('-').is_some_and(|number| {
                    !number.is_empty() && number.bytes().all(|b| b.is_ascii_digit())
                })
        })
    })
}

pub fn claude_task_launch(context: &LaunchContext<'_>, role: &str, prompt: &str) -> AgentLaunch {
    task_launch(context, role, prompt, &system_prompt())
}

/// The agent that turns a freshly scaffolded session's rough seed config into a runnable one. It runs in a
/// terminal with the normal permission prompts, so the user watches and approves what it does.
pub fn onboard_launch(context: &LaunchContext<'_>) -> AgentLaunch {
    task_launch(
        context,
        "onboarder",
        ONBOARD_FIRST_TURN,
        &onboard_system_prompt(),
    )
}

fn task_launch(context: &LaunchContext<'_>, role: &str, prompt: &str, system: &str) -> AgentLaunch {
    let stamp = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map_or(0, |elapsed| elapsed.as_nanos());
    let id = session_id(&format!("{role}:{}:{stamp}", context.branch));
    let claude = resolve_claude(context.home, context.tool_path);
    let mcp = mcp_config_json(context.state, context.binary, context.branch);
    let script = format!(
        "export PATH={path}; export TERM=xterm-256color COLORTERM=truecolor; unsetopt monitor 2>/dev/null; cd {cwd} && exec {claude} --session-id {id} --mcp-config {mcp} --append-system-prompt {system} {prompt}",
        path = shell_quote(context.tool_path),
        cwd = shell_quote(&context.cwd.to_string_lossy()),
        claude = shell_quote(&claude),
        mcp = shell_quote(&mcp),
        system = shell_quote(system),
        prompt = shell_quote(prompt),
    );
    AgentLaunch {
        holder: format!(
            "ws-{}-{}-{role}",
            context.session.replace('/', "_"),
            context.branch.replace('/', "_")
        ),
        cwd: context.cwd.to_path_buf(),
        argv: vec!["zsh".into(), "-c".into(), script],
        title: format!("Claude ({role})"),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_task_starts_a_fresh_conversation_on_its_prompt() {
        let state = StateDir::new("/tmp/pom-state");
        let context = LaunchContext {
            state: &state,
            home: Path::new("/nonexistent-home"),
            binary: Path::new("/app/pom"),
            tool_path: "/usr/bin",
            session: "demo",
            branch: "feat/x",
            is_main: false,
            cwd: Path::new("/work/demo"),
        };
        let launch = claude_task_launch(&context, "fixer", "Make it run: it's broken");
        assert_eq!(launch.holder, "ws-demo-feat_x-fixer");
        assert!(is_agent_holder(&launch.holder, "demo", "feat/x"));
        assert!(is_agent_holder(
            "ws-demo-feat_x-claude-raw-3",
            "demo",
            "feat/x"
        ));
        assert!(!is_agent_holder("ws-demo-feat_x-worker", "demo", "feat/x"));
        assert!(!is_agent_holder(
            "ws-demo-feat_x-claude-raw",
            "other",
            "feat/x"
        ));
        let script = launch.argv.last().cloned().unwrap_or_default();
        assert!(script.contains("--session-id"));
        assert!(!script.contains("--resume"));
        assert!(script.ends_with(&shell_quote("Make it run: it's broken")));
        let again = claude_task_launch(&context, "fixer", "x");
        assert_ne!(
            script.split("--session-id ").nth(1).map(|rest| &rest[..36]),
            again
                .argv
                .last()
                .and_then(|s| s.split("--session-id ").nth(1))
                .map(|rest| &rest[..36])
        );
    }

    #[test]
    fn the_onboarder_keeps_permission_prompts_and_ascii_instructions() {
        let state = StateDir::new("/tmp/pom-state");
        let context = LaunchContext {
            state: &state,
            home: Path::new("/nonexistent-home"),
            binary: Path::new("/app/pom"),
            tool_path: "/usr/bin",
            session: "demo",
            branch: "main",
            is_main: true,
            cwd: Path::new("/work/demo"),
        };
        let launch = onboard_launch(&context);
        assert_eq!(launch.holder, "ws-demo-main-onboarder");
        let script = launch.argv.last().cloned().unwrap_or_default();
        assert!(!script.contains("--dangerously-skip-permissions"));
        assert!(!script.contains("bypassPermissions"));
        assert!(script.contains("config_normalize"));
        let system = onboard_system_prompt();
        assert!(system.is_ascii());
        assert!(system.contains("{{secret.NAME}}") && system.contains("{file: ...}"));
    }

    #[test]
    fn session_ids_match_the_previous_core() {
        let id = session_id("chat:ws:feat-x");
        assert_eq!(id, "dd62e83d-9872-5064-baad-223be47ea746");
        assert_eq!(&id[14..15], "5", "version nibble");
        assert!(
            matches!(&id[19..20], "8" | "9" | "a" | "b"),
            "variant bits: {id}"
        );
        assert_eq!(id, session_id("chat:ws:feat-x"));
        assert_ne!(id, session_id("chat:main:feat-x"));
    }

    #[test]
    fn launch_resumes_an_existing_conversation() {
        let temp = tempfile::tempdir().expect("temp");
        let home = temp.path().join("home");
        let cwd = PathBuf::from("/p/workspace--feat");
        let state = StateDir::new(temp.path().join("state"));
        let context = LaunchContext {
            state: &state,
            home: &home,
            binary: Path::new("/Apps/Pomelo.app/Contents/MacOS/pomelo"),
            tool_path: "/usr/bin:/bin",
            session: "demo",
            branch: "feat",
            is_main: false,
            cwd: &cwd,
        };
        let fresh = claude_launch(&context);
        assert_eq!(fresh.holder, "ws-demo-feat-claude-raw");
        let script = &fresh.argv[2];
        let id = session_id("chat:ws:feat");
        assert!(script.contains(&format!("--session-id {id}")), "{script}");
        assert!(script.contains("--mcp-config '{\"mcpServers\""), "{script}");
        assert!(
            script.contains("cd '/p/workspace--feat' && exec 'claude'"),
            "{script}"
        );

        let transcripts = home.join(".claude/projects/-p-workspace--feat");
        std::fs::create_dir_all(&transcripts).expect("dir");
        std::fs::write(transcripts.join(format!("{id}.jsonl")), "").expect("transcript");
        assert!(claude_launch(&context).argv[2].contains(&format!("--resume {id}")));
    }

    #[test]
    fn the_launch_script_parses_and_passes_every_argument_intact() {
        let temp = tempfile::tempdir().expect("temp");
        let state = StateDir::new(temp.path().join("state"));
        let cwd = temp.path().join("it's here");
        let launch = claude_launch(&LaunchContext {
            state: &state,
            home: temp.path(),
            binary: Path::new("/bin/pomelo"),
            tool_path: "/usr/bin:/bin",
            session: "demo",
            branch: "main",
            is_main: true,
            cwd: &cwd,
        });
        let script = launch.argv[2].replacen("exec 'claude'", "printf '%s\\0'", 1);
        std::fs::create_dir_all(&cwd).expect("cwd");
        let output = std::process::Command::new("zsh")
            .args(["-f", "-c", &script])
            .output()
            .expect("zsh");
        assert!(
            output.status.success(),
            "{}",
            String::from_utf8_lossy(&output.stderr)
        );
        let args: Vec<String> = String::from_utf8_lossy(&output.stdout)
            .split('\0')
            .map(str::to_string)
            .collect();
        let prompt_at = args
            .iter()
            .position(|arg| arg == "--append-system-prompt")
            .expect("prompt flag");
        assert!(args[prompt_at + 1].starts_with("You have the `pom` MCP tools"));
        assert!(
            args[prompt_at + 1].contains("MINIO_URL"),
            "the whole prompt is one argument"
        );
        let config_at = args
            .iter()
            .position(|arg| arg == "--mcp-config")
            .expect("mcp flag");
        let config: serde_json::Value =
            serde_json::from_str(&args[config_at + 1]).expect("mcp json survives quoting");
        assert_eq!(config["mcpServers"]["pom"]["args"][2], "main");
    }

    #[test]
    fn the_prompt_is_plain_ascii() {
        assert!(system_prompt().is_ascii());
    }
}
